config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'

  namespace :admin do
    root to: 'users#index'
    resources :debtors
    resources :lenders
    resources :users, except: [:show]
    resources :organizations, except: [:show]
    resources :payments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/debtor.rb
class Debtor < ApplicationRecord
  belongs_to :debtorable, polymorphic: true
  has_many :transactions
  has_many :loans
  has_many :payments

  # validate :debtorable_exists?

  # private

  # def debtorable_exists?
  #   if self.class.where(debtorable_type: debtorable_type, debtorable_id: debtorable_id).any?
  #     errors.add(:base, 'Debtor exists for that user or organization')
  #   end
  # end
end

app/models/lender.rb
class Lender < ApplicationRecord
  belongs_to :lenderable, polymorphic: true
  has_many :transactions
end

app/models/loan.rb
class Loan < ApplicationRecord
    belongs_to :debtor
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :debtors, as: :debtorable
  has_many :lenders, as: :lenderable
end

app/models/payment.rb
class Payment < ApplicationRecord
  PAYMENT_STATE = ['pending', 'paid']
  belongs_to :debtor
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :debtor
  belongs_to :lender
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: %i[user moderator admin]

  has_many :debtors, as: :debtorable
  has_many :lenders, as: :lenderable

  def full_name
    "#{first_name} #{last_name}"
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/admin/debtors_controller.rb
class Admin::DebtorsController < AdminController
  before_action :find_debtor, only: :destroy

  def index
    @debtors = Debtor.all
  end

  def create
    @debtor = Debtor.new(debtor_params)
    if @debtor.save
      flash[:notice] = "Debtor #{@debtor.debtorable_id} was created"
      redirect_to admin_debtors_path
    else
      flash[:alert] = @debtor.errors.full_messages.first
      redirect_back(fallback_location: admin_debtors_path)
    end
  end

  def destroy
    @debtor.destroy
    flash[:alert] = "Debtor ##{@debtor.id} has been destroyed!"
    redirect_back(fallback_location: admin_debtors_path)
  end

  private

  def find_debtor
    @debtor = Debtor.find(params[:id])
  end

  def debtor_params
    params.permit(:debtorable_id, :debtorable_type)
  end
end

app/controllers/admin/lenders_controller.rb
class Admin::LendersController < AdminController
  before_action :find_debtor, only: :destroy

  def index
    @lenders = Lender.all
  end

  def create
    @lender = Lender.new(lender_params)
    if @lender.save
      flash[:notice] = "Debtor #{@lender.lenderable_id} was created"
      redirect_to admin_lenders_path
    else
      flash[:alert] = @lender.errors.full_messages.first
      redirect_back(fallback_location: admin_lenders_path)
    end
  end

  def destroy
    @lender.destroy
    flash[:alert] = "Debtor ##{@lender.id} has been destroyed!"
    redirect_back(fallback_location: admin_lenders_path)
  end

  private

  def find_lender
    @lender = Lender.find(params[:id])
  end

  def lender_params
    params.permit(:lenderable_id, :lenderable_type)
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController
  before_action :find_organization, except: [:new, :create, :index]

  def index
    @organizations = Organization.order(:id)
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.create(organization_params)
    if @organization.errors.present?
      render :new
    else
      flash[:notice] = "Organization #{@organization.name} has been created!"
      redirect_to admin_organizations_path
    end
  end

  def update
    if @organization.update(organization_params)
      flash[:notice] = "Organization #{@organization.name} has been updated!"
      redirect_to admin_organizations_path
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    flash[:alert] = "Organization #{@organization.name} has been destroyed!"
    redirect_back(fallback_location: admin_organizations_path)
  end

  private

  def find_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name, :description)
  end
end

app/controllers/admin/payments_controller.rb
class Admin::PaymentsController < AdminController
  before_action :find_payment, except: [:new, :create, :index]
  before_action :debtors_list, only: [:new, :edit, :update]

  def index
    @payments = Payment.all
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.create(payment_params)
    if @payment.errors.present?
      render :new
    else
      flash[:notice] = "Payment #{@payment.id} has been created!"
      redirect_to admin_payments_path
    end
  end

  def update
    if @payment.update(payment_params)
      flash[:notice] = "Payment #{@payment.id} has been updated!"
      redirect_to admin_payments_path
    else
      render :edit
    end
  end

  def destroy
    @payment.destroy
    flash[:alert] = "Payment #{@payment.email} has been destroyed!"
    redirect_back(fallback_location: admin_payments_path)
  end

  private

  def debtors_list
    @debtors = Debtor.all
  end

  def find_payment
    @payment = Payment.find(params[:id])
  end

  private

  def payment_params
    params.require(:payment).permit(:sum, :description, :debtor_id, :state, :paid_at)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :find_user, except: [:new, :create, :index]

  def index
    @users = User.order(:id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.errors.present?
      render :new
    else
      flash[:notice] = "User #{@user.email} has been created!"
      redirect_to admin_users_path
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "User #{@user.email} has been updated!"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:alert] = "User #{@user.email} has been destroyed!"
    redirect_back(fallback_location: admin_users_path)
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'application'
  before_action :require_admin

  private

  def require_admin
    unless current_user.try(:admin?)
      flash[:alert] = 'That panel is available only for admin!'
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :admin_namespace?

  def admin_namespace?
    self.class.parent == Admin
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def deptorable_name(debtor)
    if debtor.debtorable_type == 'User'
      debtor.debtorable.full_name
    else
      debtor.debtorable.name
    end
  end

  def lenderable_name(lender)
    if lender.lenderable_type == 'User'
      lender.lenderable.full_name
    else
      lender.lenderable.name
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/debtors/index.html.erb
<div class="row">
  <div class="col-md col-sm">
    <h2>Debtors</h2>
  </div>
</div>
<div class="row">
  <div class="col mt-3">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Debtorable id</th>
          <th scope="col">Debtorable name</th>
          <th scope="col">Type</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% @debtors.each do |debtor| %>
          <tr>
            <th scope="row"><%= debtor.id %></th>
            <td><%= debtor.debtorable_id %></td>
            <td><%= deptorable_name(debtor) %></td>
            <td><%= debtor.debtorable_type %></td>
            <td>
              <%= link_to 'Destroy', admin_debtor_path(debtor), class: "badge badge-danger", method: :delete, data: { confirm: 'Are you gonna delete that debtor?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/lenders/index.html.erb
<div class="row">
  <div class="col-md col-sm">
    <h2>Lenders</h2>
  </div>
</div>
<div class="row">
  <div class="col mt-3">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Lenderable id</th>
          <th scope="col">Lenderable name</th>
          <th scope="col">Type</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% @lenders.each do |lender| %>
          <tr>
            <th scope="row"><%= lender.id %></th>
            <td><%= lender.lenderable_id %></td>
            <td><%= lenderable_name(lender) %></td>
            <td><%= lender.lenderable_type %></td>
            <td>
              <%= link_to 'Destroy', admin_lender_path(debtor), class: "badge badge-danger", method: :delete, data: { confirm: 'Are you gonna delete that lender?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/organizations/_form.html.erb
<%= form_for [:admin, @organization] do |f| %>
  <%= render 'layouts/components/errors', errors: @organization.errors %>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, autocomplete: '\name', class: 'form-control', required: true %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 col-sm-12">
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, autofocus: true, autocomplete: 'description', class: 'form-control', required: true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/organizations/edit.html.erb
<h1>Edit organization</h1>
<%= render 'form' %>

app/views/admin/organizations/index.html.erb
<div class="row">
  <div class="col-md col-sm">
    <h2>Organizations</h2>
  </div>
  <div class="col-md-3 col-sm-3">
    <%= link_to 'Create new organization', new_admin_organization_path, class: 'btn btn-outline-success' %>
  </div>
</div>
<div class="row">
  <div class="col mt-3">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% @organizations.each do |organization| %>
          <tr>
            <th scope="row"><%= organization.id %></th>
            <td><%= organization.name %></td>
            <td><%= organization.description %></td>
            <td>
              <%= link_to 'Edit', edit_admin_organization_path(organization), class: "badge badge-warning" %>
              <%= link_to 'Make deptor', admin_debtors_path(debtorable_id: organization, debtorable_type: organization.class.name), method: :post, class: "badge badge-success" %>
              <%= link_to 'Destroy', admin_organization_path(organization), class: "badge badge-danger", method: :delete, data: { confirm: 'Are you gonna delete that organization?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/organizations/new.html.erb
<h1>Create organization</h1>
<%= render 'form' %>

app/views/admin/payments/_form.html.erb
<%= form_for [:admin, @payment] do |f| %>
  <%= render 'layouts/components/errors', errors: @payment.errors %>
  <div class="row">
     <div class="col-md-12">
        <div class="form-group">
           <%= f.label :sum %>
           <%= f.text_field :sum, autofocus: true, autocomplete: '\sum', class: 'form-control', required: true %>
        </div>
     </div>
  </div>
  <div class="row">
     <div class="col-md-12">
        <div class="form-group">
           <%= f.label :description %>
           <%= f.text_area :description, autofocus: true, autocomplete: '\description', class: 'form-control', required: true %>
        </div>
     </div>
  </div>
  <div class="row">
     <div class="col-md-12">
        <div class="form-group">
           <%= f.label :debtor %>
           <%= f.select :debtor_id, options_for_select(@debtors.map { |d| [d.debtorable.name , d.id] }, :debtor_id), {}, class: "form-control" %>
        </div>
     </div>
  </div>
  <div class="row">
     <div class="col-md-12">
        <div class="form-group">
           <%= f.label :state %>
           <%= f.select :state, options_for_select(["pending", "paid"], :state), {}, class: "form-control" %>
        </div>
     </div>
  </div>
  <div class="row">
     <div class="col-md-12">
        <div class="form-group">
           <%= f.label :paid_at %>
           <%= f.date_field :paid_at, autofocus: true, autocomplete: '\paid_at', class: 'form-control' %>
        </div>
     </div>
  </div>
  <div class="form-group">
     <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/payments/edit.html.erb
<h1>Edit Payment</h1>
<%= render 'form' %>

app/views/admin/payments/index.html.erb
<div class="row">
  <div class="col-md col-sm">
    <h2>Payments</h2>
  </div>
  <div class="col-md-3 col-sm-3">
    <%= link_to 'Create new payment', new_admin_payment_path, class: 'btn btn-outline-success' %>
  </div>
</div>
<div class="row">
  <div class="col mt-3">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Sum</th>
          <th scope="col">Description</th>
          <th scope="col">Deptor id</th>
          <th scope="col">State</th>
          <th scope="col">Paid at</th>
          <th scope="col">Created at</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% @payments.each do |payment| %>
          <tr>
            <th scope="row"><%= payment.id %></th>
            <td><%= humanized_money_with_symbol payment.sum %></td>
            <td><%= payment.description %></td>
            <td><%= payment.debtor_id %></td>
            <td><%= payment.state %></td>
            <td><%= payment.paid_at %></td>
            <td><%= payment.created_at %></td>
            <td>
              <%= link_to 'Edit', edit_admin_payment_path(payment), class: "badge badge-warning" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/payments/new.html.erb
<h1>Create Payment</h1>
<%= render 'form' %>

app/views/admin/payments/show.html.erb
<%= @payment.id %>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= render 'layouts/components/errors', errors: @user.errors %>
  <div class="row">
    <div class="col-md col-sm-12">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, autofocus: true, autocomplete: 'first name', class: 'form-control' %>
      </div>
    </div>
    <div class="col-md col-sm-12">
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, autofocus: true, autocomplete: 'last name', class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md col-sm-12">
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control', required: true %>
      </div>
    </div>
    <div class="col-md col-sm-12">
      <div class="form-group">
        <%= f.label :role %>
        <%= f.select :role, options_for_select(User.roles.keys, :role), {}, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md col-sm-12">
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: 'current-password', class: 'form-control' %>
      </div>
    </div>
    <div class="col-md col-sm-12">
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, autocomplete: 'current-password', class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Edit user</h1>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-md col-sm">
    <h2>Users</h2>
  </div>
  <div class="col-md-3 col-sm-3">
    <%= link_to 'Create new user', new_admin_user_path, class: 'btn btn-outline-success' %>
  </div>
</div>
<div class="row">
  <div class="col mt-3">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Full Name</th>
          <th scope="col">email</th>
          <th scope="col">role</th>
          <th scope="col">actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row"><%= user.id %></th>
            <td><%= user.full_name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
            <td>
              <%= link_to 'Edit', edit_admin_user_path(user), class: "badge badge-warning" %>
              <%= link_to 'Make deptor', admin_debtors_path(debtorable_id: user, debtorable_type: user.class.name), method: :post, class: "badge badge-success" %>
              <%= link_to 'Destroy', admin_user_path(user), class: "badge badge-danger", method: :delete, data: { confirm: 'Are you gonna delete that user?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<h1>Create user</h1>
<%= render 'form' %>

app/views/home/index.html.slim
= content_for(:title) { 'FinanceManagment - Main page' }
h1 Home page

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/components/header' %>
      <%= render 'layouts/components/alert' %>
      <div class="mt-3">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/components/_alert.html.erb
<% if notice %>
  <div class="alert alert-primary mt-3" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif alert %>
  <div class="alert alert-danger mt-3" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/components/_errors.html.erb
<% if errors.any? %>
  <div class="row">
    <div class="col-md-9 col-sm-12">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">
          <%= "You have #{@user.errors.count} errors:" %>
        </h4>
        <ul>
          <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <hr>
        <p class="mb-0">Please try again!</p>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/components/_header.html.erb
<% if admin_namespace? %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<% else %>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
<% end %>
  <%= link_to 'Finance managment', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <% if admin_namespace? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="adminNavbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resources
          </a>
          <div class="dropdown-menu" aria-labelledby="adminNavbarDropdown">
            <%= link_to 'Users', admin_users_path, class: "dropdown-item" %>
            <%= link_to 'Organizations', admin_organizations_path, class: "dropdown-item" %>
            <%= link_to 'Debtors', admin_debtors_path, class: "dropdown-item" %>
            <%= link_to 'Lenders', admin_lenders_path, class: "dropdown-item" %>
            <%= link_to 'Payment', admin_payments_path, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if current_user %>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to 'Admin panel', admin_root_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
        </li>
        <%= link_to 'Log out', destroy_user_session_path, class: "nav-link", method: :delete %>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>